const LANGUAGE_CODES = {
  // af: { name: 'Afrikaans', value: 'Afrikaans' },
  // sq: { name: 'Albanian', value: 'Shqip' },
  // am: { name: 'Amharic', value: 'አማርኛ' },
  ar: { name: 'Arabic', value: 'العربية' },
  // hy: { name: 'Armenian', value: 'Հայերեն' },
  az: { name: 'Azerbaijani', value: 'Azərbaycan dili' },
  // eu: { name: 'Basque', value: 'Euskara' },
  // be: { name: 'Belarusian', value: 'Беларуская' },
  // bn: { name: 'Bengali', value: 'বাংলা' },
  // bs: { name: 'Bosnian', value: 'Bosanski' },
  bg: { name: 'Bulgarian', value: 'Български' },
  //   ca: { name: 'Catalan', value: 'Català' },
  //   ceb: { name: 'Cebuano', value: 'Sinugboanon' },
  //   'zh-CN': { name: 'Chinese (Simplified)', value: '中文(简体)' },
  //   'zh-TW': { name: 'Chinese (Traditional)', value: '中文(繁體)' },
  //   co: { name: 'Corsican', value: 'Corsu' },
  //   hr: { name: 'Croatian', value: 'Hrvatski' },
  //   cs: { name: 'Czech', value: 'Čeština' },
  //   da: { name: 'Danish', value: 'Dansk' },
  //   nl: { name: 'Dutch', value: 'Nederlands' },
  //   en: { name: 'English', value: 'English' },
  //   eo: { name: 'Esperanto', value: 'Esperanto' },
  //   et: { name: 'Estonian', value: 'Eesti' },
  //   fi: { name: 'Finnish', value: 'Suomi' },
  //   fr: { name: 'French', value: 'Français' },
  //   fy: { name: 'Frisian', value: 'Frysk' },
  //   gl: { name: 'Galician', value: 'Galego' },
  //   ka: { name: 'Georgian', value: 'ქართული' },
  //   de: { name: 'German', value: 'Deutsch' },
  //   el: { name: 'Greek', value: 'Ελληνικά' },
  //   gu: { name: 'Gujarati', value: 'ગુજરાતી' },
  //   ht: { name: 'Haitian Creole', value: 'Kreyòl Ayisyen' },
  //   ha: { name: 'Hausa', value: 'Hausa' },
  //   haw: { name: 'Hawaiian', value: 'ʻŌlelo Hawaiʻi' },
  //   he: { name: 'Hebrew', value: 'עברית' },
  //   hi: { name: 'Hindi', value: 'हिन्दी' },
  //   hmn: { name: 'Hmong', value: 'Hmoob' },
  //   hu: { name: 'Hungarian', value: 'Magyar' },
  //   is: { name: 'Icelandic', value: 'Íslenska' },
  //   ig: { name: 'Igbo', value: 'Igbo' },
  //   id: { name: 'Indonesian', value: 'Bahasa Indonesia' },
  //   ga: { name: 'Irish', value: 'Gaeilge' },
  //   it: { name: 'Italian', value: 'Italiano' },
  //   ja: { name: 'Japanese', value: '日本語' },
  //   jv: { name: 'Javanese', value: 'Basa Jawa' },
  //   kn: { name: 'Kannada', value: 'ಕನ್ನಡ' },
  //   kk: { name: 'Kazakh', value: 'Қазақ тілі' },
  //   km: { name: 'Khmer', value: 'ភាសាខ្មែរ' },
  //   rw: { name: 'Kinyarwanda', value: 'Kinyarwanda' },
  //   ko: { name: 'Korean', value: '한국어' },
  //   ku: { name: 'Kurdish', value: 'Kurdî' },
  //   ky: { name: 'Kyrgyz', value: 'Кыргызча' },
  //   lo: { name: 'Lao', value: 'ລາວ' },
  //   la: { name: 'Latin', value: 'Latina' },
  //   lv: { name: 'Latvian', value: 'Latviešu' },
  //   lt: { name: 'Lithuanian', value: 'Lietuvių' },
  //   lb: { name: 'Luxembourgish', value: 'Lëtzebuergesch' },
  //   mk: { name: 'Macedonian', value: 'Македонски' },
  //   mg: { name: 'Malagasy', value: 'Malagasy' },
  //   ms: { name: 'Malay', value: 'Bahasa Melayu' },
  //   ml: { name: 'Malayalam', value: 'മലയാളം' },
  //   mt: { name: 'Maltese', value: 'Malti' },
  //   mi: { name: 'Maori', value: 'Māori' },
  //   mr: { name: 'Marathi', value: 'मराठी' },
  //   mn: { name: 'Mongolian', value: 'Монгол' },
  //   my: { name: 'Myanmar (Burmese)', value: 'မြန်မာဘာသာ' },
  //   ne: { name: 'Nepali', value: 'नेपाली' },
  //   no: { name: 'Norwegian', value: 'Norsk' },
  //   ny: { name: 'Nyanja (Chichewa)', value: 'Chi-Chewa' },
  //   or: { name: 'Odia (Oriya)', value: 'ଓଡ଼ିଆ' },
  //   ps: { name: 'Pashto', value: 'پښتو' },
  //   fa: { name: 'Persian', value: 'فارسی' },
  //   pl: { name: 'Polish', value: 'Polski' },
  //   pt: { name: 'Portuguese (Portugal, Brazil)', value: 'Português' },
  //   pa: { name: 'Punjabi', value: 'ਪੰਜਾਬੀ' },
  //   ro: { name: 'Romanian', value: 'Română' },
  //   ru: { name: 'Russian', value: 'Русский' },
  //   sm: { name: 'Samoan', value: 'Gagana Samoa' },
  //   gd: { name: 'Scots Gaelic', value: 'Gàidhlig' },
  //   sr: { name: 'Serbian', value: 'Српски' },
  //   st: { name: 'Sesotho', value: 'Sesotho' },
  //   sn: { name: 'Shona', value: 'ChiShona' },
  //   sd: { name: 'Sindhi', value: 'سنڌي' },
  //   si: { name: 'Sinhala (Sinhalese)', value: 'සිංහල' },
  //   sk: { name: 'Slovak', value: 'Slovenčina' },
  //   sl: { name: 'Slovenian', value: 'Slovenščina' },
  //   so: { name: 'Somali', value: 'Soomaali' },
  //   es: { name: 'Spanish', value: 'Español' },
  //   su: { name: 'Sundanese', value: 'Basa Sunda' },
  //   sw: { name: 'Swahili', value: 'Kiswahili' },
  //   sv: { name: 'Swedish', value: 'Svenska' },
  //   tl: { name: 'Tagalog (Filipino)', value: 'Tagalog' },
  //   tg: { name: 'Tajik', value: 'тоҷикӣ' },
  //   ta: { name: 'Tamil', value: 'தமிழ்' },
  //   tt: { name: 'Tatar', value: 'Татарча' },
  //   te: { name: 'Telugu', value: 'తెలుగు' },
  //   th: { name: 'Thai', value: 'ไทย' },
  //   tr: { name: 'Turkish', value: 'Türkçe' },
  //   tk: { name: 'Turkmen', value: 'Türkmençe' },
  //   uk: { name: 'Ukrainian', value: 'Українська' },
  //   ur: { name: 'Urdu', value: 'اردو' },
  //   ug: { name: 'Uyghur', value: 'ئۇيغۇرچە' },
  //   uz: { name: 'Uzbek', value: 'O‘zbek' },
  //   vi: { name: 'Vietnamese', value: 'Tiếng Việt' },
  //   cy: { name: 'Welsh', value: 'Cymraeg' },
  //   xh: { name: 'Xhosa', value: 'isiXhosa' },
  //   yi: { name: 'Yiddish', value: 'ייִדיש' },
  //   yo: { name: 'Yoruba', value: 'Yorùbá' },
  //   zu: { name: 'Zulu', value: 'isiZulu' },
};

module.exports = { LANGUAGE_CODES };
