export const SOCIAL_ICONS = [
  {
    value: 'facebook',
    name: 'FaceBook',
    icon: 'devicon:facebook',
    color: '#1877F2',
  },
  {
    value: 'instagram',
    name: 'Instagram',
    icon: 'skill-icons:instagram',
    color: '#E02D69',
  },
  {
    value: 'linkedin',
    name: 'Linkedin',
    icon: 'devicon:linkedin',
    color: '#007EBB',
  },
  {
    value: 'twitter',
    name: 'X (Twitter)',
    icon: 'hugeicons:new-twitter',
    color: '#00AAEC',
  },
  {
    value: 'snapchat',
    name: 'Snapchat',
    icon: 'hugeicons:snapchat',
    color: '#000000',
  },
  {
    value: 'tiktok',
    name: 'Tiktok',
    icon: 'logos:tiktok-icon',
    color: '#000000',
  },
  {
    value: 'youtube',
    name: 'Youtube',
    icon: 'openmoji:youtube',
    color: '#000000',
  },
  {
    value: 'website',
    name: 'Website',
    icon: 'iconoir:www',
    color: '#000000',
  },
  {
    value: 'locationMap',
    name: 'Location Map',
    icon: 'logos:google-maps',
    color: '#000000',
  },
  {
    value: 'other',
    name: 'Other',
    icon: 'ph:link-bold',
    color: '#000000',
  },
  {
    value: 'googleReview',
    name: 'Google Review',
    icon: 'devicon:google',
    color: '#000000',
    helperText: 'Adding the Link will show Google Review button in menu "view order" drawer',
  },
  {
    value: 'linkTree',
    name: 'Linktree',
    icon: 'simple-icons:linktree',
    color: '#000000',
  },
];
